EDS/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf import settings
from lazysignup.views import convert

from conrad import views

urlpatterns = [
    path('conrad/', include('conrad.urls')),    
    path('admin/', admin.site.urls),
    path('', views.main_home, name = 'home'),
    path('about/', views.about, name = 'about'),

    path('accounts/login/',  auth_views.LoginView.as_view(template_name='EDS/login.html'), name='login'),
    path('accounts/reset/', auth_views.PasswordResetView.as_view(template_name='EDS/password_reset.html'),
         name='password_reset'),
    path('accounts/logout/',  auth_views.LogoutView.as_view(template_name='EDS/logout.html'), name='logout'),
    path('accounts/profile/', views.profile, name='profile'),
    path('accounts/signup/', views.signup, name='signup'),

    path('convert/', convert, name = 'lazysignup_convert'),
     #    include('lazysignup.urls')),
    path('accounts/privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('accounts/password/', views.change_password, name='change_password'),
    path('password_reset/', auth_views.password_reset, name='password_reset'),
    path('password_reset/done/', auth_views.password_reset_done, name='password_reset_done'),
    path('reset/<uidb64>[0-9A-Za-z_\-]+/<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20}/',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    path('reset/done/', auth_views.password_reset_complete, name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conrad/urls.py
from django.urls import path

from . import views

app_name = "conrad"
urlpatterns = [
    path('', views.home, name='home'),
    path('gallery/<str:sort>/<str:time>/<str:group>/<int:index>/', views.gallery, name='gallery'),
    path('local/', views.userhome, name='userhome'),
    path('global/', views.globalhome, name='globalhome'),
    path('local/<int:population>/', views.local, name='local'),
    path('global/<int:population>/', views.global_game, name='global_game'),
    path('login/', views.login, name='login'),
    path('about/', views.conrad_about, name="conrad_about"),
    path('inspect/<int:id>', views.inspect, name="inspect"),
    path('ngp/', views.create_global_pop, name="ngp"),
    path('data_download/', views.data_download, name='data_download'),
    path('sandbox/', views.sandbox, name='sandbox'),
    path('data/', views.data, name='data'),
    path('learn/', views.learn, name='learn'),
    path('resources/', views.resources, name='resources'),
    path('contact/', views.contact, name='contact'),
]

conrad/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import conrad.image as image

# Create your models here.

class Artist(models.Model):
	genome = models.CharField(max_length=200)
	fitness = models.IntegerField(default = 0)
	gallery_fitness = models.IntegerField(default = 0)
	image = models.ImageField(upload_to='static/conrad/images',
							   blank=True,
							   null=True,
							   )
	image500 = models.ImageField(
							   blank=True,
							   null=True,
							   )
	generation = models.IntegerField(default = 0)
	population = models.IntegerField(default = 0)
	member = models.IntegerField(default = 0)
	seen = models.IntegerField(default = 0)
	user = models.CharField(max_length=200, default = "Default")
	created = models.DateTimeField(default=timezone.now)
	last_active = models.DateTimeField(auto_now=True)
	father = models.ManyToManyField('self', default=None)
	mother = models.ManyToManyField('self', default=None)
	voters = models.ManyToManyField(User, default=None)
	gallery_voters = models.ManyToManyField(User, related_name='+', default=None)
	alive = models.BooleanField(default=True)
	global_pop = models.BooleanField(default=False)
	def __str__(self):
		return "{0}{1}_{2}_{3}_{4}".format(self.user, '_global' if self.global_pop else '', self.population, self.generation, self.member)

	@property
	def mean_fitness(self):
		return self.gallery_fitness/max(self.seen, 1)

	@property
	def function(self):
		return image.print_gene(self.genome, 0, 1)

	
	

conrad/views.py
# Create your views here.

from django.http import HttpResponseRedirect
from .models import Artist
from django.shortcuts import render
import conrad.GA as GA
import conrad.image as image
import conrad.conrad_utils as conrad_utils
import EDS.storage_utils as storage_utils
import datetime
from django.utils import timezone
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
import re
import random
import csv
from lazysignup.decorators import allow_lazy_user
from lazysignup.utils import is_lazy_user
import math

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import views as auth_views

from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect

from django.core.files.storage import default_storage



from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect
from django.utils.translation import ugettext as _


def home(request):
	userlist = list(set([p.user for p in  Artist.objects.all()]))
	return render(request, 'conrad/home.html', {'userlist':userlist})


def conrad_about(request):
	return render(request, 'conrad/about_conrad.html')


def main_home(request):
	return render(request, 'conrad/main_home.html')


def about(request):
	return render(request, 'conrad/main_about.html')


def privacy_policy(request):
	return render(request, 'conrad/privacy.html')

def data(request):
	if is_lazy_user(request.user):
		request.session.guest = True
		request.session.modified = True
	return render(request, 'conrad/data.html')

def learn(request):
	return render(request, 'conrad/learn.html')

def resources(request):
	return render(request, 'conrad/resources.html')

def contact(request):
	return render(request, 'conrad/contact.html')


def howto(request, population):
	return render(request, 'conrad/how_to.html', {'population':population})

def profile(request):
	if not request.user.is_authenticated:
		return HttpResponseRedirect('/accounts/login/')
	if is_lazy_user(request.user):
		return HttpResponseRedirect('/accounts/login/')
	else:
		return render(request, 'conrad/profile.html')


def newgen(request, population, gen, username):
	pop = Artist.objects.filter(user=username, population=population, global_pop=False, generation=gen)
	fitness = round(sum([a.fitness for a in pop]) / len(pop), 2)
	diversity = conrad_utils.genetic_diversity(pop)
	top_image = pop.order_by('-fitness', '-created')[0]
	if not top_image.image500:
		im = GA.display(top_image.genome, size=(500,500))
		out = "{}_500.PNG".format(top_image)
		storage_utils.upload(im, 'media/'+out)
		top_image.image500 = out
		top_image.save()

	return render(request, 'conrad/end_gen.html', {'population':population, 'generation':gen, 'top_image':top_image,
											'fitness':fitness, 'diversity':diversity})


# stolen from https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html
class SignUpForm(UserCreationForm):
	# def __init__(self):
	# 	super(SignUpForm, self).__init__()
	# 	self.password1.help_text = 'Must contain at least 8 characters.'

	first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
	last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
	email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')


	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        form.fields['password1'].help_text = 'Must contain at least 8 characters.'
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
        form.fields['password1'].help_text = 'Must contain at least 8 characters.'
    return render(request, 'EDS/signup.html', {'form': form})




@allow_lazy_user
def userhome(request):
	username = request.user
	if is_lazy_user(request.user):
		request.session.guest = True

	pop_list = list(set([p.population for p in Artist.objects.filter(user=username, global_pop=False)]))
	if pop_list:
		pops = [Artist.objects.filter(user=username, population = p, global_pop=False) for p in pop_list]
		top_images = [p.filter(seen__gte=0).order_by('-fitness', '-created')[0] for p in pops]
		gens = [max([a.generation for a in p]) for p in pops]
		la = [max([a.last_active for a in p]) for p in pops]
		fitnesses = [round(sum([a.fitness for a in p.filter(seen__gte=0)])/
					len([a.fitness for a in p.filter(seen__gte=0)]), 2) for p in pops]
		varieties = [conrad_utils.genetic_diversity(pops[i].filter(generation=gens[i])) for i in range(len(pops))]
		no_to_go = [(len(pops[i].filter(generation=gens[i], seen__lte=0))) for i in range(len(pops))]
		for i in top_images:
			if i.image == '':
				im = GA.display(i.genome)
				out = "{}.PNG".format(i)
				storage_utils.upload(im, 'media/' + out)
				i.image = out
			i.save()
		top_images = [i.image.url for i in top_images]
		user_pops = [[pop_list[i], top_images[i], gens[i], fitnesses[i], varieties[i], no_to_go[i], la[i]] for i in range(len(pop_list))]
		new_pop = max(pop_list) + 1
	else:
		user_pops = []
		new_pop = 0

	context = {'user_pops':user_pops, 'username':username, 'new_pop':new_pop}
	return render(request, 'conrad/userhome.html', context)


@allow_lazy_user
def globalhome(request):
	username = request.user
	if is_lazy_user(request.user):
		request.session.guest = True

	pop = Artist.objects.filter(global_pop=True, alive=True)
	top_image = sorted(pop, key=lambda x: ((x.mean_fitness/10)**2) * (math.log(max(1, x.seen))+1), reverse=True)[0]
	gen = max([a.generation for a in pop])
	users = len(set([a.user for a in pop]))
	fits = [a.mean_fitness for a in pop.filter(seen__gte=0)]
	fitness = round(sum(fits) / len(fits), 2)
	variety = conrad_utils.genetic_diversity(pop)

	if top_image.image500 == '':
		im = GA.display(top_image.genome, size=(500, 500))
		out = "{}_500.PNG".format(top_image)
		storage_utils.upload(im, 'media/' + out)
		top_image.image500 = out
		top_image.save()

	top_image = top_image.image500.url

	pop_data = [top_image, gen, fitness, variety, users]

	context = {'pop_data':pop_data, 'username':username}
	return render(request, 'conrad/globalhome.html', context)


@allow_lazy_user
def local(request, population):
	username = str(request.user)
	if is_lazy_user(request.user):
		request.session.guest = True
	if username == 'global':
		return global_game(request, population)
	try:
		artists = request.POST.getlist('artist[]')
		scores = request.POST.getlist('score[]')


	except (KeyError, Artist.DoesNotExist):
		pass
	else:
		for i in range(len(artists)):
			a = Artist.objects.get(pk=artists[i])
			a.fitness = scores[i]
			a.gallery_fitness = scores[i]
			a.seen = True
			a.last_active = timezone.now()
			a.voters.add(request.user)
			a.save()

	if not Artist.objects.filter(population=population, user=username, global_pop=False):
		conrad_utils.newpop(30, 30, population, username)
		return howto(request, population)
	else:
		currentpop = Artist.objects.filter(seen=False, population=population, user=username, global_pop=False)
		if not currentpop:
			maxgen = max([f.generation for f in Artist.objects.filter(population=population, user=username, global_pop=False)])
			conrad_utils.newgen(Artist.objects.filter(population=population, generation=maxgen, user=username, global_pop=False))
			return newgen(request, population, maxgen, username)

	top_images = Artist.objects.filter(seen=False, population=population, user=username, global_pop=False).order_by('member')[:5]
	for i in top_images:
		if i.image == '':
			im = GA.display(i.genome)
			out = "{}.PNG".format(i)
			storage_utils.upload(im, 'media/'+out)
			i.image = out
		i.save()
	context = {'top_images': top_images, 'username':username, 'population':population}

	return render(request, 'conrad/local.html', context)

@allow_lazy_user
def global_game(request, population):
	username = str(request.user)

	if is_lazy_user(request.user):
		request.session.guest = True
		request.session.save()
		request.session.modified = True
	try:
		artists = request.POST.getlist('artist[]')
		scores = request.POST.getlist('score[]')

	except (KeyError, Artist.DoesNotExist):
		pass
	else:
		for i in range(len(artists)):
			a = Artist.objects.get(pk=artists[i])
			a.fitness += int(scores[i])
			a.gallery_fitness += int(scores[i])
			a.seen += 1
			a.last_active = timezone.now()
			a.voters.add(request.user)
			a.save()
			livepop = Artist.objects.filter(alive=True, population=population, global_pop=True)
			conrad_utils.global_mate(a, livepop, username)

	while len(Artist.objects.filter(alive=True, population=population, global_pop=True)) > 200:
		candidate = conrad_utils.cull(Artist.objects.filter(alive=True, population=population, global_pop=True))
		victim = Artist.objects.get(pk=candidate.id)
		victim.alive=False
		victim.save()

	alive_pop = Artist.objects.filter(alive=True, population=population, global_pop=True)
	maxgen = max([a.generation for a in alive_pop])
	top_images_temp = alive_pop.order_by('last_active')[:20]

	top_images = random.sample(list(top_images_temp), 5)
	for i in top_images:
		if i.image == '':
			im = GA.display(i.genome)
			out = "{}.PNG".format(i)
			storage_utils.upload(im, 'media/'+out)
			i.image = out
		i.save()
	context = {'top_images': top_images, 'population':population, 'username':username, 'maxgen':maxgen}

	return render(request, 'conrad/global.html', context)

conrad/templates/conrad/data.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


<div class="top-container">

<h1> Data </h1>

<p>
Here you can download the full population of anonymised data.</p>
</div>

{% if request.user %}

	{% if request.session.guest %}
	<p> Please <a href = "{% url 'conrad:login' %}">Create an Account</a>to download the data</p>

	{% else %}
	<p><a href = "{% url 'conrad:data_download' %}">Download the Data</a></p>
	{% endif %}

{% else %}
<p> Please <a href = "{%url 'conrad:login' %}">Create an Account</a>to download the data</p>
{% endif %}

{% endblock %}

conrad/templates/conrad/global.html
{% extends 'base.html' %}

{% block content %}
<h2> Global Genetic Art Population </h2>
<h3> User: {{ username }} &nbsp Population: {{ population }}  &nbsp Maximum Generation: {{ maxgen }}</h3>

{% if request.session.guest %}
<p> You're playing as a guest. <a href = '/accounts/signup/'> Sign Up </a> or <a href = '/accounts/login/'> Login</a> to save your creations.</p>
{% endif %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if top_images %}

{% load static %}

<link rel="stylesheet" type = "text/css" href = "{% static 'conrad/style.css' %}" />

<div class="form-container">
<form action = "{% url 'conrad:global_game' population %}" method = "post">
{% csrf_token %}
{% for artist in top_images %}
	<div id="display">
		<img src="{{ artist.image.url }}" alt="Image 01" height="200" width="200"/></label><br/>
		<p>Artist: {{ artist }}</p>
		<input type = "number" min = "1" max = "10" name = "score[]" id = "artist{{ forloop.counter }}" value = "1" />
		<input type = "hidden" name = "artist[]" value = "{{ artist.id }}" />
		<label for="artist{{ forloop.counter }}">
		<a href = '/conrad/inspect/{{ artist.id }}'>Inspect</a>
	</div>
{% endfor %}
<br/>
</div>
<div id="vote">
&nbsp;
<br/>
<input class = "submit" type = "submit" value = "Vote" />
</div>
</form>

{% endif %}

{% endblock %}

conrad/templates/conrad/globalhome.html
{% extends 'base.html' %}

{% block content %}

{% if pop_data %}
<h2> The Global Population </h2>

<p> There is only one global population, made up of 200 Artists which anybody can vote on.

	Unlike local populations, the global populations do not run through generations one at a time, destroying and creating new Artists at distinct intervals. Artists are created and destroyed in real time as you vote on them.</p>


{% if request.session.guest %}
<p> You're playing as a guest. <a href = '/accounts/signup/'> Sign Up </a> or <a href = '/accounts/login/'> Login</a> to save your creations.</p>
{% endif %}


<div class="home-main-container">
		<h2><a href="{% url 'conrad:global_game' 0 %}">Global Population</a></h2>

<div class="home-container">
<img src="{{ pop_data.0 }}" alt="Global Genetic Art Population - Top Image" height="300" width="300"/></label>

	<div class = "home-p">
		<p> 
		The global population has been evolving since the start of the site and everyone has access to it.</p>
		<p> Current stats:</p>
		<ul>
			<li>Max Generation: {{ pop_data.1 }}</li>
			<li>Average Fitness: {{ pop_data.2 }}</li>
			<li>Genetic Diversity: {{ pop_data.3 }}%</li>
			<li>Global Users: {{ pop_data.4 }}</li>
		</ul>

	<div class = "flex-container" style = "margin-top:24px;">
	<a class = "btn" style = "position:relative; left:10%; font-size:24px; font-size:24; color:#fff" href = "{%url 'conrad:global_game' 0 %}">Start Evolving</a>
	</div>
	</div>
</div>
</div>


		
		
		

{% endif %}

{% endblock %}

conrad/templates/conrad/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


<div class="top-container">

<h1> Conrad </h1>

<p>
Named for Conrad Martens, the painter who accompanied Charles Darwin on the HMS Beagle, Conrad is a simple Genetic Algorithm which designs art based on user preferences, built on the Django framework.</p>
</div>


<div class="home-main-container">
<h2><a href = "{% url 'conrad:userhome' %}">Local Population</a></h2><br/>

<div class="home-container">
	<img src="{% static 'conrad/local.PNG' %}" alt=Local Genetic Art Population" height="300" width="300"/></label>
	

	<div class = "home-p">
	<h3><a href = "{% url 'conrad:userhome' %}">Start evolving your own local population of art.</a></h3>

	<p> The first generation of images will be created entirely at random. By selecting your favourites the algorithm soon learns which sorts of images you like, and the art population will become more and more similar to your tastes.</p>
	</div>
</div>
</div>


<div class="home-main-container">
<h2><a href = "{% url 'conrad:globalhome' %}">Global Population</a></h2><br/>

<div class="home-container">
	<img src="{% static 'conrad/global.PNG' %}" alt="Global Genetic Art Population" height="300" width="300"/></label>

	<div class = "home-p">
		<h3><a href = "{% url 'conrad:globalhome' %}">Join the global population and generate art for everyone.</a></h3>
		<p> 
		The global population has been evolving since the start of the site. Everyone has access to it, and so the algorithm is attempting to find art which is appreciated by all users.</p>
	</div>
</div>
</div>


{% endblock %}

conrad/templates/conrad/how_to.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="top-container">

<h1> New Population </h1>


<div class="home-main-container">

<div class="home-container" style="width:1000;">
	<img src="{% static 'conrad/how_to.png' %}" alt=Local Genetic Art Population" height="500" /></label>

	<div class = "home-p" style="max-width: 500px;">
	<h3><a href = "{% url 'conrad:userhome' %}">You've Just Created a New Population</a></h3>

	<p> A brand new population of 50 artists is being created.</p>
	<p> Each artist will have a genome, which they use to create an image. They've been generated totally at random - so some of the images they create might be gorgeous already through pure luck - but some of them might be horrible or just plain black!</p>
	<p> Your job is to rate the images  between 1 (bad) and 10 (good). Once you've finished the generation, the algorithm will create a brand new generation based on your choices</p>
	<p> When you're ready, click below to get started</p>

	<div class = "flex-container" style = "margin-top:30px;">
	<a class = "btn" style = "position:relative; left:30%; font-size:30px;" href = "{%url 'conrad:local' population %}" style = "font-size:30; color:#fff">Get Started</a>
	<div>
	</div>
</div>
</div>




{% endblock %}

conrad/templates/conrad/local.html
{% extends 'base.html' %}

{% block content %}
<h2> Local Genetic Art Population </h2>
<h3> User: {{ username }} &nbsp Population: {{ population }}  &nbsp Generation: {{ top_images.1.generation }} &nbsp Showing members: {{ top_images.0.member }} - {{ top_images.4.member }}</h3>


{% if request.session.guest %}
<p> You're playing as a guest. <a href = '/accounts/signup/'> Sign Up </a> or <a href = '/accounts/login/'> Login</a> to save your creations.</p>
{% endif %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if top_images %}

{% load static %}

<link rel="stylesheet" type = "text/css" href = "{% static 'conrad/style.css' %}" />

<div class="form-container">
<form action = "{% url 'conrad:local' population %}" method = "post">
{% csrf_token %}
{% for artist in top_images %}
	<div id="display">
		<img src="{{ artist.image.url }}" alt="Image 01" height="200" width="200"/></label><br/>
		<p>Artist: {{ artist }}</p>
		<input type = "number" min = "1" max = "10" name = "score[]" id = "artist{{ forloop.counter }}" value = "1" required=True/>
		<input type = "hidden" name = "artist[]" value = "{{ artist.id }}" />
		<label for="artist{{ forloop.counter }}">
			<a class = "btn" href = '/conrad/inspect/{{ artist.id }}'>Inspect</a>
	</div>
{% endfor %}
<br/>
</div>
<div id="vote">
&nbsp;
<br/>
<input class = "submit" type = "submit" value = "Vote" />
</div>
</form>

{% endif %}

{% endblock %}

conrad/templates/conrad/main_home.html
{% extends 'base.html' %}

{% block content %}

{% load static %}


<div class="home-main-container">
<h2><a href = "{% url 'conrad:home' %}">Conrad</a></h2><br/>

<div class="home-container">
	<img src="{% static 'conrad/home1.png' %}" alt="Conrad Genetic Art Algorithm" height="300" width="300"/></label>

	<div class = "home-p">
		<h3><a href = "{% url 'conrad:home' %}">Genetic Art</a></h3>
		<p> 
		Conrad is a genetic algorithm which generates art. Create your own personal population of images using Conrad, join the Global Conrad population, or view the best creations in the Gallery.</p>
	</div>
</div>
</div>


<div class="home-main-container">
<h2><a href = "{% url 'about' %}">About</a></h2><br/>

<div class="home-container">
	<img src="{% static 'conrad/home2.png' %}" alt="Genetic-Algorithms.com" height="300" width="300"/></label>

	<div class = "home-p">
		<h3><a href = "{% url 'about' %}">What are Genetic Algorithms?</a></h3>
		<p> 
		Genetic Algorithms are a form of machine learning inspired by natural selection.</p>
		<p>genetic-algorithms.com is dedicated to creating interactive Genetic Algorithms to help users understand how they work.</p>
	</div>
</div>
</div>

{% endblock %}

conrad/templates/conrad/resources.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


<div class="top-container">

<h1> Resources </h1>

<p>
If you're interested in Genetic Algorithms and want to learn more, there are plenty of free courses to give you more depth. This is a very limited list, so please do <a href = "{% url 'conrad:contact' %}"> suggest more!</a></p>
</div>

<div style = "margin-top:40px; max-width:800px;">
<h3> <a href = "https://mitpress.mit.edu/books/introduction-genetic-algorithms">An Introduction to Genetic Algorithms</a></h3>
<h4> by Melanie Mitchell </h4>
<p>This 1996 book is still a superb introduction to GAs from a practical and theoretical point of view. It features thought exercises and programming exercises in every chapter, and introduces the basic concepts before moving on to some of the most pressing problems of the field (at the time and still to this day!)</p>
</div>

<div style = "margin-top:40px; max-width:800px;">
<h3> <a href = "https://mitpress.mit.edu/books/adaptation-natural-and-artificial-systems">Adaptation in Natural and Artificial Systems</a></h3>
<h4> by John H Holland</h4>
<p>Older and harder-going than Mitchell's introduction, this is a classic text on GA's that helped to shape how the field developed. Particular focus on the theoretical background to 'adaptation' more generally.</p>
</div>


<div style = "margin-top:40px; max-width:800px;">
<h3> <a href = "https://www.complexityexplorer.org/courses/">Complexity Explorer</a></h3>
<h4> Santa Fe Institute</h4>
<p>With a more general focus, these courses are great for anyone who is interested in the forces which underly natural and artificial evolution, and many other processes besides. The 'Introduction to Complexity' course (again by Melanie Mitchell) does a great job at introducing a thorny subject matter in a succint and engaging way. The section on GAs is particularly interesting (and inspired this website!)</p>
</div>


{% endblock %}

conrad/templates/conrad/sandbox.html
{% extends 'base.html' %}

{% block content %}
<h2> Conrad Sandbox </h2>

{% if error_message %}<p><strong style="color:red">{{ error_message }}</strong></p>{% endif %}


{% load static %}

<link rel="stylesheet" type = "text/css" href = "{% static 'conrad/style.css' %}" />


<form class = 'sandbox-form' action = "{% url 'conrad:sandbox' %}" method = "get">
	<div class = "flex-container">
		<div class = "left">
			<div>
				<h3> Custom Artist 1 </h3>
				<p>Enter a genome</p>
				<input type = "text" name = "image1" id = "image1" value = "{{ genome1 }}" pattern=".{0}|.{30,}"; size=42; required title="Minimum length: 30 chars)"/>
				<input class = "submit" type = "submit" value = "Generate" />
			</div>
	
			{% if image1 %}
			<br/>
			<div>
				<img src="{{ image1 }}" alt="Image 01" height="200" width="200"/></label><br/>
				<p style="font-size:15px;"> Function: {{ function1 }}</p>
			</div>
		{% endif %}
		</div>


	<div class = "right">
			<div>
				<h3>Custom Artist 2</h3>
				<p>Enter another genome</p>
				<input type = "text" name = "image2" id = "image2" value = "{{ genome2 }}" pattern=".{0}|.{30,}"; size=42; >
				<input class = "submit" type = "submit" value = "Generate" />
			</div>
		<br/>
		<div>
			{% if image2 %}
				<img src="{{ image2 }}" alt="Image 01" height="200" width="200"/></label><br/>
				<p style="font-size:15px;"> Function: {{ function2 }}</p>
			{% endif %}
		</div>
	</div>
	<br>
	</div>
	<div>
		{% if image1 and image2 %}
		<h3> Create Offspring </h3>
		<input type="radio" id="offspring"
     name="offspring" value="True">
    <label for="contactChoice1">True</label>

    <input type="radio" id="offspring"
     name="offspring" value="False">
    <label for="contactChoice1">False</label>
		<input class = "submit" type = "submit" value = "Generate" />
		{% endif %}
		{% if image3 %}
				<img src="{{ image3 }}" alt="Image 01" height="200" width="200"/></label><br/>
				<p> Genome: {{ genome3 }}</p>
				<p style="font-size:15px;"> Function: {{ function3 }}</p>
		{% endif %}
	</div>
</form>






{% endblock %}