EDS/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf import settings
from lazysignup.views import convert

from conrad import views

urlpatterns = [
    path('conrad/', include('conrad.urls')),    
    path('admin/', admin.site.urls),
    path('', views.main_home, name = 'home'),
    path('about/', views.about, name = 'about'),

    path('accounts/login/',  auth_views.LoginView.as_view(template_name='EDS/login.html'), name='login'),
    path('accounts/reset/', auth_views.PasswordResetView.as_view(template_name='EDS/password_reset.html'),
         name='password_reset'),
    path('accounts/logout/',  auth_views.LogoutView.as_view(template_name='EDS/logout.html'), name='logout'),
    path('accounts/profile/', views.profile, name='profile'),
    path('accounts/signup/', views.signup, name='signup'),

    path('convert/', convert, name = 'lazysignup_convert'),
     #    include('lazysignup.urls')),
    path('accounts/privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('accounts/password/', views.change_password, name='change_password'),
    path('password_reset/', auth_views.password_reset, name='password_reset'),
    path('password_reset/done/', auth_views.password_reset_done, name='password_reset_done'),
    path('reset/<uidb64>[0-9A-Za-z_\-]+/<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20}/',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    path('reset/done/', auth_views.password_reset_complete, name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conrad/urls.py
from django.urls import path

from . import views

app_name = "conrad"
urlpatterns = [
    path('', views.home, name='home'),
    path('gallery/<str:sort>/<str:time>/<str:group>/<int:index>/', views.gallery, name='gallery'),
    path('local/', views.userhome, name='userhome'),
    path('global/', views.globalhome, name='globalhome'),
    path('local/<int:population>/', views.local, name='local'),
    path('global/<int:population>/', views.global_game, name='global_game'),
    path('login/', views.login, name='login'),
    path('about/', views.conrad_about, name="conrad_about"),
    path('inspect/<int:id>', views.inspect, name="inspect"),
    path('ngp/', views.create_global_pop, name="ngp"),
    path('data_download/', views.data_download, name='data_download'),
    path('sandbox/', views.sandbox, name='sandbox'),
    path('data/', views.data, name='data'),
    path('learn/', views.learn, name='learn'),
    path('resources/', views.resources, name='resources'),
    path('contact/', views.contact, name='contact'),
]

EDS/views.py
from django.shortcuts import render

def main_home(request):
	return render(request, 'conrad/main_home.html')
	
def about(request):
	return render(request, 'conrad/about.html')
	

templates/EDS/convert.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
{% load i18n %}


<div class="home-main-container" style="width: 1000px;">
<h2>Convert Your Guest Account</h2><br/>

<div class="home-container" style="width: 1000px;">
  <img src="{% static 'conrad/sign_up.PNG' %}" alt="Create Genetic Art User Account" height="500" width="500"/></label>

  <div class = "home-p" style="max-width: 500px;">
    <h2>Convert your Account</h2>
    <p> You're currently using a guest account, sign up here to save your populations and convert your account to a real user account</p>
    <form method="post">
      {% csrf_token %}
      {% for field in form %}
        <p>
          {{ field.label_tag }}<br>
          {{ field }}
          {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
          {% endfor %}
        </p>
      {% endfor %}
    <button type="submit">Sign up</button>

    <p> You can read our <a href = '/accounts/privacy_policy'>Privacy Policy</a> here.</p>
  </form>

   
  <div>
</div>
</div>
</div>
</div>

</br>

</div>

  
{% endblock %}

templates/EDS/login.html
{% extends "base.html" %}

{% block content %}

{% load static %}

<div class="top-container">

    <h1> Login </h1>

    {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    {% if next %}
        {% if user.is_authenticated %}
        <p>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p>
        {% else %}
        <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}
</div>


    <div class="home-main-container">
        <h2><a href = "{% url 'signup' %}"> Sign Up</a></h2><br/>

        <div class="home-container">
            <img src="{% static 'conrad/sign_up.png' %}" alt=Local Genetic Art Population height="300" width="300"/></label>
            
            <div class = "home-p">
                <h3><a href = "{% url 'signup' %}">Don't have an account? </a></h3>
                <p>Sign Up <a href = '/accounts/signup/'>here</a> to create an account so you can save and resume your populations, and show off your creations in the <a href = "{% url 'conrad:gallery' 'best' 'alltime' 'all' 0 %}">Gallery</a></p>
            </div>

        </div>
    </div>


    <div class="home-main-container">
        <h2>Login</h2><br/>

        <div class="home-container">
            <img src="{% static 'conrad/login.png' %}" alt="Login to Genetic Algorithms" height="300" width="300"/></label>

            <div class = "home-p">

                <h3>Already have an account?</h3>

                <p> Sign in below to see your populations, top images, and more </p>
                       
                <form method="post" action="{% url 'login' %}">
                {% csrf_token %}
                <table>
                <tr>
                    <td>{{ form.username.label_tag }}</td>
                    <td>{{ form.username }}</td>
                </tr>
                <tr>
                    <td>{{ form.password.label_tag }}</td>
                    <td>{{ form.password }}</td>
                </tr>
                </table>
                <input type="submit" value="login" />
                <input type="hidden" name="next" value="{{ next }}" />
                </form>

                <p><a href="{% url 'password_reset' %}">Lost password?</a></p>
            </div>
        </div>
    </div>

    {% if next %}

    <div class="home-main-container">
        <h2><a href= "{{ next }}0">Continue as a Guest</a></h2><br/>
        <div class="home-container">
            <img src="{% static 'conrad/guest.png' %}" alt="Login to Genetic Algorithms" height="300" width="300"/></label>

            <div class = "home-p">
                       
                <h3><a href= "{{ next }}0">Don't want to Sign Up?</a></h3>
                <p>You won't be able to save or resume your population if you <a href= "{{ next }}0">continue as a Guest.</a></p>

            </div>
        <div>
    </div>

{% endif %}

{% endblock %}

templates/EDS/logout.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<p>You have successfully logged out. You can log back in below</p>

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{# Assumes you setup the password_reset view in your URLconf#}
<p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}

templates/EDS/password_change.html
{% extends 'base.html' %}
{% load i18n static %}
{% load admin_urls %}

{% block extrahead %}{{ block.super }}
<script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
{% endblock %}
{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />{% endblock %}
{% block bodyclass %}{{ block.super }} {{ opts.app_label }}-{{ opts.model_name }} change-form{% endblock %}
{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
&rsaquo; <a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>
&rsaquo; <a href="{% url opts|admin_urlname:'change' original.pk|admin_urlquote %}">{{ original|truncatewords:"18" }}</a>
&rsaquo; {% trans 'Change password' %}
</div>
{% endblock %}
{% endif %}
{% block content %}<div id="content-main">
<form action="{{ form_url }}" method="post" id="{{ opts.model_name }}_form">{% csrf_token %}{% block form_top %}{% endblock %}
<input type="text" name="username" value="{{ original.get_username }}" style="display: none" />
<div>
{% if is_popup %}<input type="hidden" name="_popup" value="1" />{% endif %}
{% if form.errors %}
    <p class="errornote">
    {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
{% endif %}

<p>{% blocktrans with username=original %}Enter a new password for the user <strong>{{ username }}</strong>.{% endblocktrans %}</p>

<fieldset class="module aligned">

<div class="form-row">
  {{ form.password1.errors }}
  {{ form.password1.label_tag }} {{ form.password1 }}
  {% if form.password1.help_text %}
  <div class="help">{{ form.password1.help_text|safe }}</div>
  {% endif %}
</div>

<div class="form-row">
  {{ form.password2.errors }}
  {{ form.password2.label_tag }} {{ form.password2 }}
  {% if form.password2.help_text %}
  <div class="help">{{ form.password2.help_text|safe }}</div>
  {% endif %}
</div>

</fieldset>

<div class="submit-row">
<input type="submit" value="{% trans 'Change password' %}" class="default" />
</div>

</div>
</form></div>
{% endblock %}

 

templates/EDS/signup.html
{% extends 'base.html' %}

{% block content %}

{% load static %}


<div class="home-main-container" style="width: 1000px;">
<h2>Create an Account</h2><br/>

<div class="home-container" style="width: 1000px;">
  <img src="{% static 'conrad/sign_up.PNG' %}" alt="Create Genetic Art User Account" height="500" width="500"/></label>

  <div class = "home-p" style="max-width: 500px;">
    <h2>Sign up</h2>
    <form method="post">
      {% csrf_token %}
      {% for field in form %}
        <p>
          {{ field.label_tag }}<br>
          {{ field }}
          {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
          {% endfor %}
        </p>
      {% endfor %}
    <button type="submit">Sign up</button>

    <p> You can read our <a href = '/accounts/privacy_policy'>Privacy Policy</a> here.</p>
  </form>
  <div>
</div>
</div>
</div>
</div>

</br>

</div>

  
{% endblock %}